# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import chorus_pb2 as chorus__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    import warnings
    warnings.warn(
        f'grpcio {GRPC_VERSION} may be older than generated code expects '
        f'({GRPC_GENERATED_VERSION}). Upgrade grpcio or regenerate stubs.',
        RuntimeWarning,
        stacklevel=1,
    )


class VectorStreamStub:
    """---------------------------------------------------------------------------
    Services
    ---------------------------------------------------------------------------

    Raw float32 streaming (used by fabric.py for low-level tensor transport).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamVectors = channel.stream_stream(
                '/chorus.VectorStream/StreamVectors',
                request_serializer=chorus__pb2.VectorPayload.SerializeToString,
                response_deserializer=chorus__pb2.VectorAck.FromString,
                _registered_method=True)
        self.SendVector = channel.unary_unary(
                '/chorus.VectorStream/SendVector',
                request_serializer=chorus__pb2.VectorPayload.SerializeToString,
                response_deserializer=chorus__pb2.VectorAck.FromString,
                _registered_method=True)


class VectorStreamServicer:
    """---------------------------------------------------------------------------
    Services
    ---------------------------------------------------------------------------

    Raw float32 streaming (used by fabric.py for low-level tensor transport).
    """

    def StreamVectors(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendVector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectorStreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamVectors': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamVectors,
                    request_deserializer=chorus__pb2.VectorPayload.FromString,
                    response_serializer=chorus__pb2.VectorAck.SerializeToString,
            ),
            'SendVector': grpc.unary_unary_rpc_method_handler(
                    servicer.SendVector,
                    request_deserializer=chorus__pb2.VectorPayload.FromString,
                    response_serializer=chorus__pb2.VectorAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chorus.VectorStream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chorus.VectorStream', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VectorStream:
    """---------------------------------------------------------------------------
    Services
    ---------------------------------------------------------------------------

    Raw float32 streaming (used by fabric.py for low-level tensor transport).
    """

    @staticmethod
    def StreamVectors(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/chorus.VectorStream/StreamVectors',
            chorus__pb2.VectorPayload.SerializeToString,
            chorus__pb2.VectorAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chorus.VectorStream/SendVector',
            chorus__pb2.VectorPayload.SerializeToString,
            chorus__pb2.VectorAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WrapperServiceStub:
    """Server Wrapper service (runs on DB node).
    DLL Drivers connect here to receive pushed row events and issue queries.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Hello = channel.unary_unary(
                '/chorus.WrapperService/Hello',
                request_serializer=chorus__pb2.HelloRequest.SerializeToString,
                response_deserializer=chorus__pb2.HelloResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/chorus.WrapperService/Subscribe',
                request_serializer=chorus__pb2.HelloRequest.SerializeToString,
                response_deserializer=chorus__pb2.RowEvent.FromString,
                _registered_method=True)
        self.AckEvents = channel.stream_unary(
                '/chorus.WrapperService/AckEvents',
                request_serializer=chorus__pb2.RowEventAck.SerializeToString,
                response_deserializer=chorus__pb2.VectorAck.FromString,
                _registered_method=True)
        self.Query = channel.unary_unary(
                '/chorus.WrapperService/Query',
                request_serializer=chorus__pb2.QueryRequest.SerializeToString,
                response_deserializer=chorus__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.Write = channel.unary_unary(
                '/chorus.WrapperService/Write',
                request_serializer=chorus__pb2.WriteRequest.SerializeToString,
                response_deserializer=chorus__pb2.WriteAck.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/chorus.WrapperService/Health',
                request_serializer=chorus__pb2.HealthRequest.SerializeToString,
                response_deserializer=chorus__pb2.HealthResponse.FromString,
                _registered_method=True)


class WrapperServiceServicer:
    """Server Wrapper service (runs on DB node).
    DLL Drivers connect here to receive pushed row events and issue queries.
    """

    def Hello(self, request, context):
        """Handshake — driver registers itself; wrapper validates version.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Wrapper pushes vectorized row events to the driver (server-side streaming).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AckEvents(self, request_iterator, context):
        """Driver sends acks back for consumed row events (client-side streaming).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Driver asks wrapper to run a similarity query against the DB index.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request, context):
        """Driver sends a write-behind write to the DB via wrapper.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health check — both sides can call this.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WrapperServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Hello': grpc.unary_unary_rpc_method_handler(
                    servicer.Hello,
                    request_deserializer=chorus__pb2.HelloRequest.FromString,
                    response_serializer=chorus__pb2.HelloResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=chorus__pb2.HelloRequest.FromString,
                    response_serializer=chorus__pb2.RowEvent.SerializeToString,
            ),
            'AckEvents': grpc.stream_unary_rpc_method_handler(
                    servicer.AckEvents,
                    request_deserializer=chorus__pb2.RowEventAck.FromString,
                    response_serializer=chorus__pb2.VectorAck.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=chorus__pb2.QueryRequest.FromString,
                    response_serializer=chorus__pb2.QueryResponse.SerializeToString,
            ),
            'Write': grpc.unary_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=chorus__pb2.WriteRequest.FromString,
                    response_serializer=chorus__pb2.WriteAck.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=chorus__pb2.HealthRequest.FromString,
                    response_serializer=chorus__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chorus.WrapperService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chorus.WrapperService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WrapperService:
    """Server Wrapper service (runs on DB node).
    DLL Drivers connect here to receive pushed row events and issue queries.
    """

    @staticmethod
    def Hello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chorus.WrapperService/Hello',
            chorus__pb2.HelloRequest.SerializeToString,
            chorus__pb2.HelloResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/chorus.WrapperService/Subscribe',
            chorus__pb2.HelloRequest.SerializeToString,
            chorus__pb2.RowEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AckEvents(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/chorus.WrapperService/AckEvents',
            chorus__pb2.RowEventAck.SerializeToString,
            chorus__pb2.VectorAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chorus.WrapperService/Query',
            chorus__pb2.QueryRequest.SerializeToString,
            chorus__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chorus.WrapperService/Write',
            chorus__pb2.WriteRequest.SerializeToString,
            chorus__pb2.WriteAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chorus.WrapperService/Health',
            chorus__pb2.HealthRequest.SerializeToString,
            chorus__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
