{{- if and .Values.tls.enabled .Values.tls.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.certSecret }}
  labels:
    app.kubernetes.io/name: {{ include "prismlib.name" . }}
type: kubernetes.io/tls
stringData:
  tls.crt: |
{{ .Values.tls.certificate | nindent 4 }}
  tls.key: |
{{ .Values.tls.privateKey | nindent 4 }}
{{- end }}
