{{- if .Values.auth.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.apiKeySecret }}
  labels:
    app.kubernetes.io/name: {{ include "prismlib.name" . }}
type: Opaque
stringData:
  PRISM_API_KEYS: {{ join "," .Values.auth.apiKeys | quote }}
{{- end }}
